###
### Retrieve top products within a category
GET http://20.244.56.144/test/companies/AMZ/categories/Laptop/products?top=10&minPrice=1&maxPrice=10000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzEyMTU1OTMwLCJpYXQiOjE3MTIxNTU2MzAsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6IjZkYTIwMjYxLWQ5MzAtNDVmNS1iZjE2LWE2ZjlkNGNhNGEzOSIsInN1YiI6ImtrNDU2M0Bzcm1pc3QuZWR1LmluIn0sImNvbXBhbnlOYW1lIjoiU1JNIElOU1RJVFVURSBPRiBTQ0lFTkNFIEFORCBURUNITk9MT0dZIiwiY2xpZW50SUQiOiI2ZGEyMDI2MS1kOTMwLTQ1ZjUtYmYxNi1hNmY5ZDRjYTRhMzkiLCJjbGllbnRTZWNyZXQiOiJETkpCa3pxdmVNR1NaZGtDIiwib3duZXJOYW1lIjoiS1BWSVNITlVTQUkiLCJvd25lckVtYWlsIjoia2s0NTYzQHNybWlzdC5lZHUuaW4iLCJyb2xsTm8iOiJSQTIxMTEwMDMwMTExMzUifQ.WVmFeP22uues2ufMV9ov1yul53kFHQ1onV-8wkpNo3U

###
GET http://20.244.56.144/test/companies/AMZ//categories/Laptop/products/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzEyMTUzMzYyLCJpYXQiOjE3MTIxNTMwNjIsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6IjZkYTIwMjYxLWQ5MzAtNDVmNS1iZjE2LWE2ZjlkNGNhNGEzOSIsInN1YiI6ImtrNDU2M0Bzcm1pc3QuZWR1LmluIn0sImNvbXBhbnlOYW1lIjoiU1JNIElOU1RJVFVURSBPRiBTQ0lFTkNFIEFORCBURUNITk9MT0dZIiwiY2xpZW50SUQiOiI2ZGEyMDI2MS1kOTMwLTQ1ZjUtYmYxNi1hNmY5ZDRjYTRhMzkiLCJjbGllbnRTZWNyZXQiOiJETkpCa3pxdmVNR1NaZGtDIiwib3duZXJOYW1lIjoiS1BWSVNITlVTQUkiLCJvd25lckVtYWlsIjoia2s0NTYzQHNybWlzdC5lZHUuaW4iLCJyb2xsTm8iOiJSQTIxMTEwMDMwMTExMzUifQ.MpYCoppHmciDd4UziLR1Gqswk5HPm328n57oOp9HVqM

###
GET http://localhost:5000/companies/AMZ/categories/Laptop/products?top=10&minPrice=1&maxPrice=10000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzEyMTU1OTMwLCJpYXQiOjE3MTIxNTU2MzAsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6IjZkYTIwMjYxLWQ5MzAtNDVmNS1iZjE2LWE2ZjlkNGNhNGEzOSIsInN1YiI6ImtrNDU2M0Bzcm1pc3QuZWR1LmluIn0sImNvbXBhbnlOYW1lIjoiU1JNIElOU1RJVFVURSBPRiBTQ0lFTkNFIEFORCBURUNITk9MT0dZIiwiY2xpZW50SUQiOiI2ZGEyMDI2MS1kOTMwLTQ1ZjUtYmYxNi1hNmY5ZDRjYTRhMzkiLCJjbGllbnRTZWNyZXQiOiJETkpCa3pxdmVNR1NaZGtDIiwib3duZXJOYW1lIjoiS1BWSVNITlVTQUkiLCJvd25lckVtYWlsIjoia2s0NTYzQHNybWlzdC5lZHUuaW4iLCJyb2xsTm8iOiJSQTIxMTEwMDMwMTExMzUifQ.WVmFeP22uues2ufMV9ov1yul53kFHQ1onV-8wkpNo3U
###

GET http://20.244.56.144/test/companies/FLP/categories/Laptop/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzEyMTU1OTMwLCJpYXQiOjE3MTIxNTU2MzAsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6IjZkYTIwMjYxLWQ5MzAtNDVmNS1iZjE2LWE2ZjlkNGNhNGEzOSIsInN1YiI6ImtrNDU2M0Bzcm1pc3QuZWR1LmluIn0sImNvbXBhbnlOYW1lIjoiU1JNIElOU1RJVFVURSBPRiBTQ0lFTkNFIEFORCBURUNITk9MT0dZIiwiY2xpZW50SUQiOiI2ZGEyMDI2MS1kOTMwLTQ1ZjUtYmYxNi1hNmY5ZDRjYTRhMzkiLCJjbGllbnRTZWNyZXQiOiJETkpCa3pxdmVNR1NaZGtDIiwib3duZXJOYW1lIjoiS1BWSVNITlVTQUkiLCJvd25lckVtYWlsIjoia2s0NTYzQHNybWlzdC5lZHUuaW4iLCJyb2xsTm8iOiJSQTIxMTEwMDMwMTExMzUifQ.WVmFeP22uues2ufMV9ov1yul53kFHQ1onV-8wkpNo3U